sonyxperiadev/device-sony-kumano

platform.mk
Android 10 changed the way libhardware is allowed to find modules, and
this doesn't work through symlinks anymore. For more information, see
the commit that removes the symlink from hardware/camera/Android.mk in
common, and the relevant change in libhardware:
https://android.googlesource.com/platform/hardware/libhardware/+/e448a05fecab601c59b89a2f948e1ad18050e40f%5E%21/#F0
Instead, set the vendor variant propery, that points libhardware to load
camera.qcom.so from any of the predefined search folders.
I don't think
```make
PRODUCT_PACKAGES += \
camera.sm8150
```
is warranted anymore.
=> camera: Set the hardware variant to `qcom'.

platform.mk
The Kumano platform requires a 64 bit camera HAL.
=> platform: use 64 bit camera implementation

platform.mk
This HAL is essential to get the QTI Haptics Vibrator working.
P.S.: https://portland.source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/vibrator
=> [KUMANO] platform: Add QTI Haptics Vibrator HAL

platform.mk
When creating an otapackage, we definitely want to also push the
vbmeta in order to get the verifier to work as intended, otherwise
the only solution would be to disable verification in the vbmeta,
leading to big security issues.
=> [KUMANO] platform: Add vbmeta to AB_OTA_PARTITIONS

sepolicy_platform/genfs_contexts
Various domains (which all have access to sysfs_msm_subsys) try to read
the npu subsystem:
libmdmdetect: Failed to open /sys/bus/msm_subsys/devices/subsys4/name: Permission denied
Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
netmgrd : avc: denied { read } for name="name" scontext=u:r:netmgrd:s0 tcontext=u:object_r:sysfs:s0 tclass=file
Signed-off-by: MarijnS95 <marijns95@gmail.com>
=> genfs_contexts: Label npu as sysfs_msm_subsys.

platform.mk
For https://github.com/sonyxperiadev/device-sony-common/pull/671
Kumano uses its own QTI vibrator HAL, the default one at version 1.0
should be excluded from the build.
=> [2/2] platform: Set TARGET_VIBRATOR_V1_2 to exclude default @1.0.

rootdir/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini
Configure WCNSS to expose a secondary interface, wlan1, which is used
for concurrent AP while wlan0 runs the STA.
=> [KUMANO] WCNSS: Enable concurrent STA/AP on wlan1 interface.

rootdir/vendor/ueventd.rc
The leds on Kumano are located under a different SPMI PMIC path, and the
attributes found under the individual nodes are different on the k4.14
driver (adhering mostly to "standard" Linux paths).
Tested on Griffin, our lights HAL is now able to fully control the LEDs without "permission denied" errors.
=> ueventd: Update Tri-LED paths to pm8150l and match k4.14 structure.

PlatformConfig.mk
The kernel and HAL gained support for the ET603 sensor found in Kumano
devices. Remove DEVICE_NO_FPC to compile this HAL and enable fingerprint
authentication.
=> [3/4] PlatformConfig: Enable FPC.

rootdir/vendor/ueventd.rc
Ipacm runs as radio and needs to access the ipa kernel device. This
follows stock.
Likewise, adpl and friends need the appropriate user and group as well.
---
Other platforms need a similar change to `/dev/ipa` but have to be checked first, just in case letting `ipacm` loose starts breaking other things.
=> ueventd: Set radio user+group on /dev/ipa*.

PlatformConfig.mk, platform.mk
See https://github.com/sonyxperiadev/device-sony-common/pull/669
No need to set it in platform. Simplifies code for future refactors
Unify this into platform here from the individual tama device repos.
Don't guard TARGET_NEEDS_DTBOIMAGE by TARGET_COMPILE_WITH_MSM_KERNEL because it's unused if in-tree kernel compilation isn't being done.
=> [2/3] Kernel rework

overlay/frameworks/base/core/res/res/values/config.xml
Kumano devices support this sensor and odm compatibility is introduced
in v5: when the device is locked, hold the phone up like you're about to
take a picture and the camera opens.
=> [KUMANO] overlay: configure camera lift trigger sensor

platform.mk, rootdir/vendor/etc/audio_policy_configuration.xml, rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml, rootdir/vendor/etc/common_primary_audio_policy_configuration.xml
The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.
=> [KUMANO] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

platform.mk, rootdir/vendor/etc/audio_platform_info.xml
This patchset brings up audio on AOSP based userspace on SoMC Kumano
and sets it up for 24-bits playback, dual mic, noise cancellation, voice-spk/voice-handset.
Device specific PRs depends on this patchset, which HAS to be merged in bulk with:
https://github.com/sonyxperiadev/device-sony-griffin/pull/7
https://github.com/sonyxperiadev/device-sony-bahamut/pull/5
Enjoy!
=> [KUMANO] Bring up audio on AOSP based userspace

platform.mk
Add the full support for Secure Element (eSE and UICC) on SoMC Kumano platform,
as supported by the PN554/557 NFC chips.
This patchset is essential to support all features in Kumano NFC.
=> [KUMANO] Add NFC eSE and UICC support

platform.mk, rootdir/vendor/etc/sound_trigger_mixer_paths_wcd9340.xml, rootdir/vendor/etc/sound_trigger_platform_info.xml
This adds the Sound Trigger configuration for the SoMC SM8150
Kumano platform, imported from stock release 55.1.A.3.149.
Tested on SoMC SM8150 Kumano Griffin DSDS
=> [KUMANO] platform: Add sound trigger configuration for SoMC SM8150 Kumano

rootdir/vendor/etc/fstab.kumano
Makes things neater with the stage-separated mounting logic in Q and later.
=> fstab: Split into early and latemount, reserve 128M on /data

platform.mk, rootdir/vendor/etc/aosp_routes_primary_audio_policy_configuration.xml, rootdir/vendor/etc/audio_io_policy.conf, rootdir/vendor/etc/audio_policy_configuration.xml, rootdir/vendor/etc/caf_primary_audio_policy_configuration.xml, rootdir/vendor/etc/caf_routes_primary_audio_policy_configuration.xml
This patchset adds support for the CodeAurora Foundation (CAF) Audio
HAL extended paths and offloading, while still retaining compatibility
with the Audio HAL for Qualcomm devices provided in the Google's AOSP
repositories.
This patchset has to be *and will be* replicated on all platforms whenever
testing gets complete on each.
Tested on Sony SM8150 Kumano Griffin DSDS.
P.S.: It's amazing!
=> [KUMANO] Add CodeAurora Foundation Audio HAL advanced paths support

rootdir/vendor/etc/init/init.kumano.pwr.rc
This platform had "totally" bad configuration for power management:
first of all, we were trying to disable retention on L3, but...
surprise! the kernel does not even support it!
Then, there was a major issue about the bus-dcvs and entire
devfreq configuration for basically all of the internal devices:
we were * for some reason * trying to write by using wildcards,
which is not supported in Android init scripts: that was messing
up the entire platform sleep, locking the RPMh in active state.
=> [KUMANO] [MASTER] vendor: init: kumano-power: Cleanup and fix power parameters

platform.mk
The optimal offload buffer size is 32kb on SM8150.
=> [KUMANO] platform: Set optimal audio offload buffer size

rootdir/vendor/etc/caf_common_primary_audio_policy_configuration.xml
The AUDIO_OUTPUT_FLAG_FAST on RAW seems to be activating
the ULL path, which doesn't work, on this platform.
Please note that ULL here means PROAUDIO, which is way less
latency than the old ultra low latency, and it's also using more CPU
for very little reasons: this is a phone.
This commit may be temporary: if we can activate this mode for
professional grade audio (using phone as an amp for musical
instruments and such -- for some reason) then we will reintroduce
this thing.
For now, having FAST in leads to many sound breakages, especially
in Android games nor anything else requesting RAW output.
------------------------
This PR fixes DSP lockups and loss of audio on the Kumano platform.
Tested on SM8150 Kumano Griffin DSDS.
=> [KUMANO] [URGENT] vendor: caf: audio_policy_configuration: Remove FAST from raw

rootdir/vendor/etc/audio_platform_info.xml
Import the missing mappings for CAF HAL migration from
55.1.A.3.149.
=> [KUMANO] [Q-MR1] audio_platform_info: Add missing mappings from 55.1.A.3.149

rootdir/vendor/etc/caf_common_primary_audio_policy_configuration.xml
The ULL path was fixed in Griffin and Bahamut mixer_paths: it is now
safe to re-enable it platform-wide.
=> [KUMANO] [Q-MR1] Re-Enable Ultra Low Latency path

platform.mk
Kumano does not have a Secure Element reader in the NFC. UICC host card emulation is supported by all our platforms and will be moved to common. Unnecessary `SecureElement` app dependencies are removed as well.
=> [KUMANO] [Q/R] [1/2] Drop unsupported NFC eSE

rootdir/vendor/etc/fstab.kumano
On google msm-kernel-4.14 stable branch, these configs is enabled and used by Android 11.
```
CONFIG_FS_ENCRYPTION_INLINE_CRYPT=y
CONFIG_FS_VERITY=y
CONFIG_FS_VERITY_BUILTIN_SIGNATURES=y
```
Since we already upgraded to stock 11, new bootloader require this feature.
We need this flag to decrypt data partition on CAF LA.UM.9.12 kernel with latest bootloader, or decryption will be failed.
=> [master] kumano: fstab: Enable inlinecrypt flag for data

sepolicy_platform/file_contexts
`gpt_block_device` is a custom SODP invention while AOSP already defines `root_block_device` for exactly this purpose; that is already used for `mmcblk0` on MMC platforms.
=> [KUMANO] [Q/R] sepolicy: Use root_block_device for sda instead of gpt_block_device

rootdir/vendor/etc/fstab.kumano
Similar to https://github.com/sonyxperiadev/device-sony-seine/pull/32
This reverts commit 8253144257fa9316e4af22ad831e226ae284a08c.
Kumano is not on CAF LA.UM.9.12 and likely won't end up there anyway.
This patch prevents properly working devices from booting with kernel
4.14 (snippet from seine):
E EXT4-fs (mmcblk0p86): Unrecognized mount option "inlinecrypt" or missing value
I init    : [libfs_mgr]__mount(source=/dev/block/bootdevice/by-name/userdata,target=/data,type=ext4)=-1: Invalid argument
Reverting this patch restores normal device functionality.
=> [KUMANO] [master] Revert "kumano: fstab: Enable inlinecrypt flag for data"

rootdir/vendor/etc/camera/camxoverridesettings.txt
These flags are providing a stabler autofocus by disabling partial
metadata and sets face detection in real-time, therefore improving
FD latency.
=> [KUMANO] [Q-MR1] vendor: camx: Add flags for stabler autofocus and faster face-detection

rootdir/vendor/etc/camera/camxoverridesettings.txt
These flags are providing a stabler autofocus by disabling partial
metadata and sets face detection in real-time, therefore improving
FD latency.
=> [KUMANO] [R-MR1] vendor: camx: Add flags for stabler autofocus and faster face-detection

rootdir/vendor/etc/camera/camxoverridesettings.txt
These flags are providing a stabler autofocus by disabling partial
metadata and sets face detection in real-time, therefore improving
FD latency.
=> [KUMANO] [MASTER] vendor: camx: Add flags for stabler autofocus and faster face-detection

platform.mk, rootdir/vendor/etc/system_properties.xml
Imported from vendor-qcom-opensource-media as of 182649923d3813e2e539a0e36d83b3e70dcfcc4a:
https://github.com/sonyxperiadev/vendor-qcom-opensource-media/tree/182649923d3813e2e539a0e36d83b3e70dcfcc4a
Required for https://github.com/sonyxperiadev/local_manifests/pull/127 on S.
=> [S-mr1] mediacodec: Import system_properties from CAF.
